'use strict';
// "[Data Entry] Customer Creation Request" emails -> Dealer Portal accounts.
//
// Today a person reads one of these and types it into the portal by hand. The
// email is already APPROVED by the time it arrives (the sample was approved by
// arun.sharma@cartrends.in), so nothing here decides anything — it only moves
// what a human already agreed to.
//
// The mail is a label/value table, so the parser keys on the LABELS and never
// on row position: a column added to that template must not silently shift
// every field by one.
const store = require('../store');

// Label in the email -> field we hand to the portal. Written loosely because
// the same template is generated by a script that has changed wording before
// ("Mobile" / "Mobile No", "Customer / Firm Name" / "Firm Name").
const FIELDS = [
  // Vendor mails say "Vendor Name" where customer mails say "Customer / Firm
  // Name". Missing this meant every vendor request parsed with no name at all.
  ['name', /customer\s*\/?\s*firm\s*name|firm\s*name|customer\s*name|vendor\s*name/i],
  ['businessType', /business\s*type/i],
  ['category', /customer\s*category/i],
  ['gstNo', /gstin|gst\s*no/i],
  ['pan', /\bpan\b/i],
  ['contactPerson', /contact\s*person/i],
  ['phone', /mobile|phone/i],
  ['email', /^e-?mail$/i],
  ['address', /^address$/i],
  ['city', /^city$/i],
  ['state', /^state$/i],
  ['pin', /pin\s*code|pincode/i],
  ['creditDays', /credit\s*period/i],
  ['creditLimit', /credit\s*limit/i],
  ['paymentTerms', /payment\s*terms/i],
  ['transportMode', /transport\s*mode/i],
  ['salesPerson', /associate\s*sales\s*person/i],
  ['requestee', /requestee\s*email/i],
  ['remarks', /^remarks$/i],

  // Inventory Creation requests carry a different set of labels.
  ['partNo', /^part\s*no\.?$/i],
  ['partName', /^part\s*name$/i],
  ['brand', /^brand\s*name$/i],
  ['mrp', /^mrp(\s*\(rs\)?\.?\)?)?$/i],
  ['hsnCode', /^hsn\s*code$/i],
  ['taxRate', /^tax\s*rate$/i],
  ['bulkRows', /bulk\s*rows\s*parsed/i],

  // Vendor-only labels. Captured so they can be REPORTED as unstorable rather
  // than vanishing silently between the mail and the portal — the Veedol
  // request was titled "ONLY ADD BANK DETAIL", which is exactly the thing this
  // API cannot write.
  ['bankHolder', /bank\s*account\s*holder/i],
  ['bankName', /^bank\s*name$/i],
  ['accountNumber', /account\s*number/i],
  ['ifsc', /^ifsc$/i],
  ['brandsSupplied', /brands\s*supplied/i],
  ['dispatchMode', /dispatch\s*mode/i],
  ['freightTerms', /freight\s*terms/i],
  ['leadTime', /lead\s*time/i],
];

// The portal has no field for these, so they are captured, reported, and NOT
// silently dropped — a PAN that never reaches the portal is a compliance gap
// someone has to know about.
const NOT_IN_PORTAL = [
  'pan',
  'paymentTerms',
  'transportMode',
  'salesPerson',
  // Vendor mails carry bank and logistics terms the portal has no field for.
  // The Veedol request was literally titled "ONLY ADD BANK DETAIL" — exactly
  // the thing that cannot be written through this API.
  'bankHolder',
  'bankName',
  'accountNumber',
  'ifsc',
  'brandsSupplied',
  'dispatchMode',
  'freightTerms',
  'leadTime',
];

const EMPTY = /^(-|na|n\/?a|none|nil|)$/i;

function clean(v) {
  const t = String(v == null ? '' : v)
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return EMPTY.test(t) ? '' : t;
}

// Pull "label: value" pairs out of either the HTML table or the plain-text
// version of the same mail. Both shapes appear depending on the mail client
// that forwarded it.
function readPairs(body) {
  const pairs = [];
  const html = String(body || '');

  // HTML table rows: <tr><td>Label</td><td>Value</td></tr>
  const rowRe = /<tr[^>]*>([\s\S]*?)<\/tr>/gi;
  let m;
  while ((m = rowRe.exec(html))) {
    const cells = [...m[1].matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map((c) => clean(c[1]));
    if (cells.length >= 2 && cells[0]) pairs.push([cells[0].replace(/:$/, ''), cells.slice(1).find(Boolean) || '']);
  }
  if (pairs.length) return pairs;

  // Plain text: "Label : Value" or "Label\tValue", one per line.
  for (const line of html.replace(/<[^>]+>/g, '\n').split(/\r?\n/)) {
    const t = line.trim();
    if (!t) continue;
    const kv = t.match(/^([A-Za-z][A-Za-z /().-]{2,40}?)\s*[:\t]\s*(.*)$/);
    if (kv) pairs.push([kv[1].trim(), clean(kv[2])]);
  }
  return pairs;
}

function parseRequest(subject, body) {
  const pairs = readPairs(body);
  if (!pairs.length) return null;

  const out = {};
  for (const [label, value] of pairs) {
    for (const [field, re] of FIELDS) {
      if (re.test(label) && out[field] === undefined) {
        out[field] = clean(value);
        break;
      }
    }
  }

  // The request id is the audit trail — it links the portal account back to
  // the approval that authorised it.
  const id = String(subject || '').match(/\b(CUST|VEND|REQ|MRP|DISC)-\d{6}-\d{6}-[A-Z0-9]+\b/i);
  out.requestId = id ? id[0].toUpperCase() : null;
  // The prefix decides what gets created, and they go to different endpoints.
  // The SUBJECT is the authority, not the fields: a vendor mail and a customer
  // mail carry almost the same labels.
  const prefix = out.requestId ? out.requestId.split('-')[0] : '';
  out.kind =
    { CUST: 'customer', VEND: 'vendor', REQ: 'inventory', MRP: 'mrp', DISC: 'discount' }[prefix] || 'unknown';

  // Numbers, once, here — so no caller has to remember that the mail writes
  // "30" for days and "100000" for a limit.
  out.creditDays = out.creditDays ? parseInt(String(out.creditDays).replace(/\D/g, ''), 10) || null : null;
  out.creditLimit = out.creditLimit ? parseFloat(String(out.creditLimit).replace(/[^\d.]/g, '')) || null : null;
  out.phone = store.normPhone(out.phone || '');

  // City, state and PIN have no field of their own in the portal, so they join
  // the address rather than being thrown away.
  const tail = [out.city, out.state, out.pin].map(clean).filter(Boolean).join(', ');
  if (tail && out.address && !out.address.includes(tail)) out.address = `${out.address}, ${tail}`;

  return out;
}

// USERNAME: the firm name in small letters, each space an underscore.
//   "SUCHA SINGH AUTOMOBILES" -> "sucha_singh_automobiles"
// Founder, 12 Sep: a space becomes "_", it is not simply removed. Anything
// else (&, ., /) becomes an underscore too and runs are collapsed, so
// "M/S  Kalra   Motors" cannot come out as "m_s__kalra___motors".
function usernameFor(fields) {
  return String(fields.name || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 40)
    .replace(/_+$/g, '');
}

// PASSWORD: the contact person's first name in small letters, then @123.
//   "Baljinder Singh" -> "baljinder@123"
// Founder, 12 Sep: all lowercase, and the suffix is @123 - it used to be
// the current year.
// Falls back to the firm's first word when no contact person was given, so a
// request is never blocked on a missing optional field.
function passwordFor(fields) {
  // Requesters sometimes put the phone number in the Contact Person box. A
  // password of "9540979093@123" is not what the rule means, so anything
  // without letters falls back to the firm name.
  const contact = clean(fields.contactPerson);
  // "M/S" is not a name: without this the fallback password for
  // "M/S Kalra Motors" came out as "ms@123".
  const firm = clean(fields.name).replace(/^s*ms*[/.]s*s.?s*/i, "");
  const source = /[A-Za-z]/.test(contact) ? contact : firm;
  const first = String(source).split(/\s+/)[0] || 'user';
  return first.toLowerCase().replace(/[^a-z0-9]/g, '') + '@123';
}

// Everything that must be true before an account is created. Returns the list
// of problems; empty means go ahead.
function validate(fields) {
  const problems = [];
  if (!fields.requestId) problems.push('request id not found in the subject');

  // MRP and discount changes are still done by hand in super admin: the portal
  // has no field to write an MRP through (PUT /parts/{part_no} does not carry
  // one), so pretending otherwise would mean guessing at an endpoint that
  // moves prices on live orders.
  if (fields.kind === 'mrp' || fields.kind === 'discount') {
    problems.push(`${fields.kind} changes are not automated — do this in super admin`);
    return problems;
  }

  if (fields.kind === 'inventory') {
    // create-part requires exactly these three.
    if (!fields.partNo) problems.push('part no missing');
    if (!fields.partName) problems.push('part name missing');
    if (!fields.brand) problems.push('brand missing');
    // "Bulk Rows Parsed" means the request covered a spreadsheet of parts, and
    // this mail shows only one of them. Creating that single row would quietly
    // drop the rest.
    if (fields.bulkRows && !/^n\/?a$/i.test(fields.bulkRows) && parseInt(fields.bulkRows, 10) > 1) {
      problems.push(`this is a bulk request (${fields.bulkRows} rows) — the mail shows only one`);
    }
    return problems;
  }

  if (fields.kind === 'unknown') {
    problems.push('unrecognised request type');
    return problems;
  }

  // customer / vendor
  if (!fields.name) problems.push('firm name missing');
  if (!fields.phone || fields.phone.length < 10) problems.push('mobile missing or not 10 digits');
  if (fields.gstNo && !/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$/i.test(fields.gstNo.replace(/\s/g, ''))) {
    problems.push(`GSTIN "${fields.gstNo}" is not a valid 15-character GSTIN`);
  }
  return problems;
}

// The portal has NO field for any of these — verified against the live API and
// a real account record, which carries 23 fields and not one of them holds a
// PAN, a bank account or an IFSC. So this is not work waiting for someone: a
// person entering the request by hand could not store them either. They stay
// where they already are, in the request mail and finance's own records.
//
// Reported once, as a fact, never as a task. Telling the team to "enter these
// manually" would invent work that cannot be done, and a notice like that is
// ignored within a week — taking the real warnings with it.
function droppedFields(fields) {
  return NOT_IN_PORTAL.filter((f) => clean(fields[f])).map((f) => `${f}=${fields[f]}`);
}


// Home Branch Dealer. The mail never carries it, and the portal API does not
// demand it — but an account without one is a thinner record than the team
// types by hand, so it is worked out from where the customer is.
//
// Founder’s rule: Rajasthan is served out of Mansarovar (Jaipur); Delhi,
// Haryana and the rest go to Bijwasan. Ids read from the live portal
// (GET /dealers/branches/list) rather than guessed:
//
//     23  BIJWASAN WAREHOUSE        Delhi
//   1078  MAANSAROVAR WAREHOUSE     Jaipur, Rajasthan
//   1079  GURUGRAM WAREHOUSE        Haryana
//   1080  NOIDA WAREHOUSE           Uttar Pradesh
//    460  KAROL BAGH WAREHOUSE
//
// Only the two the founder named are used. The others are listed so the
// mapping can be widened without going back to the API.
const BRANCH_BIJWASAN = 23;
const BRANCH_MANSAROVAR = 1078;

// Rajasthan, however the mail spells it. State first, then city, then the
// address — the mail has a State field, but it is sometimes "-".
const RAJASTHAN_STATE = /\braj(asthan)?\b/i;
const RAJASTHAN_CITY =
  /\b(jaipur|jodhpur|udaipur|kota|ajmer|bikaner|alwar|sikar|bhilwara|bharatpur|pali|sriganganagar|chittorgarh|mansarovar|sanganer)\b/i;

// 23 -> "Bijwasan", 1078 -> "Mansarovar": for the summary, the card, the report.
function branchName(id) {
  return Number(id) === BRANCH_MANSAROVAR ? 'Mansarovar' : Number(id) === BRANCH_BIJWASAN ? 'Bijwasan' : id ? 'branch ' + id : null;
}

function branchFor(fields) {
  const state = clean(fields.state);
  const city = clean(fields.city);
  const address = clean(fields.address);
  // The State field is the most reliable when it is filled in at all.
  if (state && RAJASTHAN_STATE.test(state)) return BRANCH_MANSAROVAR;
  if (city && (RAJASTHAN_CITY.test(city) || RAJASTHAN_STATE.test(city))) return BRANCH_MANSAROVAR;
  // Last resort: the address line, which usually carries the city and state
  // even when the separate fields are blank.
  if (address && (RAJASTHAN_STATE.test(address) || RAJASTHAN_CITY.test(address))) return BRANCH_MANSAROVAR;
  return BRANCH_BIJWASAN;
}

// Role on the portal. Founder, 12 Sep: BOTH a customer and a vendor account
// are created as "dealer" - which is also the API’s own default. Until then
// a customer was created with the "customer" role.
function userTypeFor() {
  return 'dealer';
}

// "Also register this customer as a Vendor" is a real duplicate account with
// a separate Odoo partner. It is ticked ONLY when the mail says the firm is
// both — never inferred, because an unwanted duplicate is worse than a
// missing one and somebody has to delete it by hand.
const BOTH_RE = /\b(both\s*(customer\s*(and|&|\/)\s*vendor|vendor\s*(and|&|\/)\s*customer)|customer\s*(and|&|\+|\/)\s*vendor|vendor\s*(and|&|\+|\/)\s*customer|also\s*(a\s*)?vendor|also\s*(a\s*)?customer)\b/i;

function isBoth(fields) {
  return BOTH_RE.test([fields.businessType, fields.category, fields.remarks].filter(Boolean).join(' | '));
}
function buildAccount(fields, year) {
  // A part has no login; only customer and vendor accounts do.
  if (fields.kind === 'inventory') {
    return {
      ...fields,
      // "18%" -> 18. The portal wants a number.
      gstPercent: fields.taxRate ? parseFloat(String(fields.taxRate).replace(/[^\d.]/g, '')) || null : null,
      mrpValue: fields.mrp ? parseFloat(String(fields.mrp).replace(/[^\d.]/g, '')) || null : null,
    };
  }
  return {
    ...fields,
    username: usernameFor(fields),
    password: passwordFor(fields),
    // Worked out here rather than in the portal client, so the reasoning
    // sits with the request it came from.
    branchId: fields.kind === 'vendor' ? null : branchFor(fields),
    userType: userTypeFor(),
    alsoVendor: fields.kind === 'customer' && isBoth(fields),
    alsoCustomer: fields.kind === 'vendor' && isBoth(fields),
  };
}

module.exports = {
  parseRequest,
  usernameFor,
  passwordFor,
  validate,
  droppedFields,
  buildAccount,
  readPairs,
  branchFor,
  branchName,
  userTypeFor,
  isBoth,
  BRANCH_BIJWASAN,
  BRANCH_MANSAROVAR,
};
